---
title: "DEA"
output: html_notebook
---

 

```{r}
#install.packages('frontier')
#install.packages('xlsx')
#install.packages('lpSolve')
#install.packages('micEcon')
#install.packages("micEcon", repos="http://R-Forge.R-project.org")

require('xlsx') # lo?d xlsx package
require('lpSolve') # load lpSolve package
require('micEcon')
require('frontier')


```

```{r}

#The input variable is the OPEX located at second column of the data matrix. 
#The output variables are at columns 3 (NETWORK), 4 (MWH) and 5 (CU?TOMERS) 
#of the data matrix. 
#The selection of inputs and outputs variables can be done by the following 
#commands:
inputs <- data.frame(data[2]) # input variable at second column of the data matrix
outputs<-data.frame(data[c(3,4,5)]) # output variables?
N <- dim(data)[1] # the number of DMUs is equal to number of rows of data matrix 
s <- dim(inputs)[2] # number of input variables, in this case s = 1
m <- dim(outputs)[2] # number of output variables, in this case m = 3


```

```{r}

#require(lpSolve) # ?oad lpSolve package
results<-lp("max",as.numeric(f.obj),f.con,f.dir,f.rhs,scale=0,compute.sens=TRUE) # lp solve lp is a function available on lpSolve package

multipliers <- results$solution # u and v
efficiency <- results$objval # theta
lambdas <- results$duals[seq(1,N)] #lambda

```

```{r}

#CRS Model

f.rhs <- c(rep(0,1,N),1) 
f.dir <- c(rep("<=",1,N),"=") 
aux <- cbind(-1*inputs,outputs)

#loop of N DMUs

for (i in 1:N) {
 f.obj <- c(0*rep(1,s),as.numeric(outputs[i,]))
 f.con <- rbind(aux ,c(as.numeric(i?puts[i,]), rep(0,1,m))) 
 results <- lp ("max",as.numeric(f.obj), f.con, f.dir, f.rhs,scale=0, compute.sens=TRUE)
 if (i==1) {
 weights <- results$solution
 effcrs <- results$objval
 lambdas <- results$duals[seq(1,N)] 
 } else {
 weights <- rbind(weights, ?esults$solution)
 effcrs <- rbind(effcrs , results$objval)
 lambdas <- rbind(lambdas, results$duals[seq(1,N)] )
 }
}


```

```{r}

# merge the efficiency and multipliers
spreadsheet <- cbind(effcrs,weights)
# assign the utilities' names to the spreadsheet?rows
rownames(spreadsheet) <- data[,1]
# assign the variables names to the spreadsheet columns
colnames(spreadsheet) <- c('efficiency',names(inputs),names(outputs)) 

# record file by xlsReadWrite package
write.xls(spreadsheet ,"resultscrs.xls",colNames = ?RUE,sheet = 1,from = 1)
# or record file by xlsx package
write.xlsx(spreadsheet ,"resultscrs.xls",col.names = TRUE )
           
```


```{r}
# duals variables
spreadsheet<-lambdas
# assign the utilities' names to the spreadsheet rows and columns
rownames(?preadsheet)<-data[,1] 
colnames(spreadsheet)<- data[,1] 
# record file by xlsReadWrite package
write.xls(spreadsheet ,"dualscrs.xls",colNames = TRUE,sheet = 1,from = 1)
# or record file by xlsx package
write.xlsx(spreadsheet ,"dualscrs.xls",col.names = TRUE)


```

```{r}
par(mar=c(10,5,1,10),xpd=TRUE) # set plot margin
palette(gray(0:8 / 8)) # set color palette
virtual<-weights[,(s+1):(s+m)]*outputs # virtual outputs
rownames(virtual)<-data[,1] # assign utilities' names to the rows of the object virtual
bar?lot(t(virtual),col=palette()[c(1,4,7)],ylab="Efficiency",cex.axis=1,cex.lab=1,cex.names=1,las=3)
legend("topright",inset=c(-0.45,0),colnames(virtual),fill=palette()[c(1,4,7)],bty="n") # add legend

```

```{r}
par(mar=c(10,5,1,1)) # set plot margin
palette?gray(0:8 / 8) # set color palette
rownames(lambdas)<-data[,1] # assigns utilities' names to the rows of duals variables matrix
colnames(lambdas)<-data[,1] # assigns utilities' names to the colimns of duals variables matrix
peer<-which(apply(lambdas,2,sum)?0) # identifies reference units (efficiency units)
barplot(t(lambdas[,peer]),col=palette()[c(1,4,7)],cex.axis=1,cex.lab=1,cex.names=1,las=3)
legend("topright",colnames(lambdas)[peer],fill=palette()[c(1,4,7)],bty="n") # add legend

```


```{r}
#The differe?ce between CRS and VRS models resides in the unconstrained variable u0
 
#This variable can be modeled by the difference of two non negative variables (u0 = u+ - u- , where u+ >= 0 and u- >=0)

#VRS Model

f.rhs <- c(rep(0,1,N),1) 
f.dir<-c(rep("<=",1,N), "=") 
aux <- cbind(-1*inputs,outputs,1,-1) 
for (i in 1:N) {
 f.obj<-c(rep(0,1,s),as.numeric(outputs[i,]),1,-1) # 1 and -1 represents u+ - u-
 f.con <- rbind(aux,c(as.numeric(inputs[i,]),rep(0,1,m),0,0))
 results <- lp ("max",as.numeric(f.obj), f.con, f.dir? f.rhs,scale=1, compute.sens=TRUE)
 multipliers <- results$solution
 u0 <- multipliers[s+m+1]-multipliers[s+m+2] 
 if (i==1) {
 weights <- c(multipliers[seq(1,s+m)],u0)
 effvrs <- results$objval
 lambdas <- results$duals[seq(1,N)] 
 } else {
 weights<-rbin(weights,c(multipliers[seq(1,s+m)],u0))
 effvrs <- rbind(effvrs , results$objval)
 lambdas <- rbind(lambdas,results$duals[seq(1,N)])
 }
} 


```

```{r}
spreadsheet<-cbind(effvrs,weights) # merge de results
rownames(spreadsheet)<-data[,1] # assign the util?ties' names to spreadsheet rows 
colnames(spreadsheet)<-c('efficiency',names(inputs), names(outputs),'u0')
# record file by xlsReadWrite package
write.xls(spreadsheet,"resultsvrs.xls",colNames = TRUE,sheet = 1,from = 1) # record file
# or record file by xl?x package
write.xlsx(spreadsheet,"resultsvrs.xls",col.names = TRUE) # record file


```

```{r}
par(mar=c(10,5,1, 8),xpd=TRUE) # set plot margin
scale <- effcrs/effvrs
spreadsheet <- cbind(effcrs,effvrs,scale)
rownames(spreadsheet) <- data[,1]
colnames(spr?adsheet) <- c("CRS","VRS","SE")
barplot(t(spreadsheet), 
col=palette()[c(1,4,7)],ylab="Efficiency",beside=TRUE,cex.axis=1,cex.lab=1,cex.names=1,las=3)
legend("topright",inset=c(-0.2,0),colnames(spreadsheet),fill=palette()[c(1,4,7)],bty="n") # add legend

```

```{r}
#References
#Angulo-Meza, L.; Estellita Lins, M.P. Review of methods for increasing discrimination in data
#envelopment analysis, Annals of Operational Research, 116, pp. 225-242, 2002.
#Banker, R.D.; Charnes, A. & Cooper, W.W. Some models for es?imating technical and scale
#inefficiencies in data envelopment analysis. Management Science, 30, 1078-1092, 1984.
#Bogetoft, P., Otto, L. Benchmarking with DEA, SFA and R, Springer Science, 2011.
#Charnes, A.; Cooper, W.W. & Rhodes, E. Measuring the Effic?ency of Decision
#Making Units. European Journal of Operational Research, 2, 1978.
#Coelli, T.J.; Rao, D.S.P.; O'Donnell, C.J.; Battese, G.E. An introduction to efficiency and productivity
#analysis, Springer, 2005.
#Cook, W.D.; Seiford, L.M. Data Envelopm?nt Analysis (DEA) - Thirty years on, European Journal of
#Operational Research, 192, pp. 1-17, 2009.
#Cooper, W.W.; Seiford, L.M.; Tone, K. Data Envelopment Analysis: A comprehensive text with
#models, applications, references and DEA-Solver Software, Kluw?r Academic Publishers, 2002.
#El-Mahgary, S.; Lahdelma, R. Data Envelopment Analysis: Visualizing the results, European
#Journal of Operational Research, 85, pp. 700-710, 1995.
#Guo, P.; Tanaka, H. Fuzzy DEA: a perceptual evaluation method, Fuzzy Sets and ?ystems, 119, pp.
#149-160, 2001.
#Ragsdale, C.T. Spreadsheet modeling & decision analysis: a practical introduction to management
#science. 4.ed. Thomson South-Western, 2004.
#R Development Core Team R: A language and environment for statistical computing.?R Foundation
#for Statistical Computing, Vienna, Austria. URL http://www.R-project.org/, 2011.
#Verzani, J. Using R for introductory statistics, Chapman & Hall/ CRC Press, 2005

```


```{r}
#Extract the coefficients from stochastic frontier models returne? by frontier.
data( front41Data )
sfaResult <- sfa( log( output ) ~ log( capital ) + log( labour ),
data = front41Data )
coef( sfaResult, which = "ols" )
coef( sfaResult, which = "grid" )
coef( sfaResult )

```

